# WARNING - Generated by {fusen} from dev/flat_plot_urgara.Rmd: do not edit by hand

<<<<<<< HEAD
test_that("plot_add_logo works", {
  expect_true(inherits(plot_add_logo, "function"))
})
=======
# test_that("plot_add_logo works", {
#   expect_true(inherits(plot_add_logo, "function")) 
# })
>>>>>>> 467edd424d4727f4aa58d2bad5856ef469206fb4
