# WARNING - Generated by {fusen} from dev/flat_plot_urgara.Rmd: do not edit by hand

#' plot charge diagram
#' 
#' plot a charge diagram from the "tab_charge" object created by plot_diag_charge()
#' 
#' @param data data passed from plot_diag_charge
#' @param tab_charge table created by fct_tab_charge
#' @inheritParams plot_diag_charge
#'
#' @return a ggplot
#' @noRd
fct_plot_charge <- function(data, tab_charge, max_LOS){
  #computation of the number of entry/exit per hour
  tab_entry <- data %>%
    dplyr::filter(LOS < max_LOS) %>%
    dplyr::mutate(Hour = lubridate::hour(dh_entry) + 1,
                  Hour = factor(Hour, levels = c(1:24))) %>%
    dplyr::group_by(Hour, .drop = F) %>%
    dplyr::count() %>%
    dplyr::mutate(Hour = as.numeric(as.character(Hour)),
                  n_days = dplyr::first(tab_charge$n_days),
                  n_strata = dplyr::first(tab_charge$n_strata),
                  n_avg = n/(n_days*n_strata)) %>%
    dplyr::ungroup()

  tab_exit <- data %>%
    dplyr::filter(LOS < max_LOS) %>%
    dplyr::mutate(Hour = lubridate::hour(dh_exit) + 1,
                  Hour = factor(Hour, levels = c(1:24))) %>%
    dplyr::group_by(Hour, .drop = F) %>%
    dplyr::count() %>%
    dplyr::mutate(Hour = as.numeric(as.character(Hour)),
                  n_days = dplyr::first(tab_charge$n_days),
                  n_strata = dplyr::first(tab_charge$n_strata),
                  n_avg = n/(n_days*n_strata)) %>%
    dplyr::ungroup()
  
  #Creation of a color palet
  pal1 <- RColorBrewer::brewer.pal(8, "Accent")
  pal2 <- RColorBrewer::brewer.pal(8, "Dark2")
  pal3 <- RColorBrewer::brewer.pal(8, "Set2")
  if(tab_charge %>% dplyr::filter(H_entry < 0) %>% sum(.$n) > 0){#at least one patient from the day before => add black to the front of the palette
    pal <- c("black", pal1, pal2, pal3)
  } else {#if no patients are from the day before black is not used
    pal <- c(pal1, pal2, pal3)
  }
  
  #plot rendering
  plot <- ggplot2::ggplot(tab_charge, ggplot2::aes()) +
    ggplot2::geom_density(ggplot2::aes(y = n_avg, x = as.numeric(Hour), fill = factor(H_entry, levels = c("-1", 0:23))),
                          stat = "identity",  position = "stack", color = NA) +
    ggplot2::geom_line(ggplot2::aes(y = n_avg, x = Hour, color = "Nombre d'entr\u00E9es"), data = tab_entry, linewidth = 1.2) +
    ggplot2::geom_line(ggplot2::aes(y = n_avg, x = Hour, color = "Nombre de sorties"), data = tab_exit, linewidth = 1.2) +
    ggplot2::scale_fill_manual(values = pal) +
    ggplot2::scale_x_continuous(name = "", breaks = seq(1,24, by = 1),
                                labels = paste0("< ", seq(1,24, by = 1), "h")) +
    ggplot2::scale_y_continuous(name = "Nombre moyen de patients", breaks = scales::pretty_breaks(10)) +
    ggplot2::scale_color_manual(name = "", values = c("Nombre d'entr\u00E9es" = "darkgreen", "Nombre de sorties" = "darkred")) +
    ggplot2::coord_cartesian(xlim = c(1,24), ylim = c(0,NA)) +
    ggpubr::theme_pubclean() +
    ggplot2::guides(fill = "none") +
    ggplot2::theme(text=ggplot2::element_text(family="serif", size=15)) +
    ggplot2::theme(legend.position = "bottom",
                   legend.key = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
  
    return(plot)
}
