# WARNING - Generated by {fusen} from dev/flat_plot_urgara.Rmd: do not edit by hand

#' Charge table
#' 
#' Internal function. Makes a charge table with one line per hour of the day (entry) per hour of the day (exit) and returns a charge table used to plot a charge diagram
#' 
#' @param data tibble with two columns, dh_entry and dh_exit
#' @inheritParams plot_diag_charge
#' 
#' @return a tibble
#' 
#' @noRd
fct_tab_charge <- function(data, from, to, max_LOS){
  #denominator
  n_days <- as.numeric(1 + difftime(to, from, units = "days"))
  if("strata" %in% names(data)){
    n_strata <- length(unique(data$strata))
  } else{n_strata = 1}
 
  #winsorisation of entry and exit to from and to
  data$entry_corrected_fact = lubridate::date(data$dh_entry) < from
  data$dh_entry_corrected = dplyr::if_else(data$entry_corrected_fact,
                                           lubridate::ymd_hms(paste(from, "00:00:01")),
                                           data$dh_entry)
  
  data$exit_corrected_fact = lubridate::date(data$dh_exit) > to
  data$dh_exit_corrected = dplyr::if_else(data$exit_corrected_fact,
                                          lubridate::ymd_hms(paste(to, "23:59:59")),
                                          data$dh_exit)

  #Computation of intermediary variables
  data_interm <- data %>%
    dplyr::mutate(#recomputation LOS and entry times after winsorization
      LOS = as.numeric(difftime(dh_exit_corrected, dh_entry_corrected, units = "mins")),
      H_entry = lubridate::hour(dh_entry_corrected),
      H_exit = lubridate::hour(dh_exit_corrected),
      entry_minute = H_entry*60 + lubridate::minute(dh_entry_corrected)#entry time in minutes since midnight
    ) %>%
    dplyr::select(entry_minute, LOS, entry_corrected_fact, H_entry, H_exit) %>%
    dplyr::mutate(exit_minute = entry_minute + LOS,
                  H_exit_comp = exit_minute %/% 60,#hour of exit with 00h of entry day (can be over 23h59)
                  H_exit_corrected = dplyr::if_else(H_exit_comp > 23, 23, as.numeric(H_exit)),#winsorizing it to 23hxx
                  exit_corrected_fact = as.numeric(H_exit_comp > 23),
                  nb_cycles = H_exit_comp %/% 24,#number of times 24h fit in the LOS
                  H_exit_last_cycle = H_exit,
                  H_entry = dplyr::if_else(entry_corrected_fact, -1, as.numeric(H_entry)))

  #Number of "full cycles" to add (patient present from 00h01 to 23h59)
  nb_H24_add = data_interm  %>%
    dplyr::filter(nb_cycles > 0) %>%
    dplyr::summarise(nb_cycle_tot = sum(nb_cycles - 1)) %>%
    dplyr::pull(nb_cycle_tot)

  #table of "full cycles" 
  tab_full_day_supp <- tibble::tibble(
    H_entry = rep(-1, nb_H24_add),
    H_exit = rep(23, nb_H24_add),
    exit_corrected_fact = 1
  ) %>%
    dplyr::mutate_all(as.numeric)

  #table of "half cycles" to add (patient arrived the day before and leaves this day)
  tab_final_day <- tibble::tibble(#ajout de x lignes correpsond à des passages -1 à "heure de sortie dernier cycle)
    H_entry = -1,
    H_exit = data_interm %>% dplyr::filter(nb_cycles > 0) %>% dplyr::pull(H_exit_last_cycle),
    exit_corrected_fact = 0
  ) %>%
    dplyr::mutate_all(as.numeric)

  #merge of full cycles, half cycles and first days
  data_calc_charge = dplyr::bind_rows(data_interm %>% dplyr::select(H_entry, H_exit = H_exit_corrected, exit_corrected_fact),
                                      tab_full_day_supp,
                                      tab_final_day)

  #Speed up following computation by merging indentical rows
  data_calc_charge_agreg = data_calc_charge %>%
    dplyr::group_by(H_entry, H_exit, exit_corrected_fact) %>%
    dplyr::count()
  
  #For each hour of the day, count the number of patient present from wich time of arrival (-1 = day before)
  tab_n = lapply(seq(1, 24, by = 1), function(H){
    data_calc_charge_agreg %>%
      dplyr::filter((H_entry < H & H_exit >= H) |
                      (H_entry == H -1 & H_exit == H - 1 & exit_corrected_fact == 0) |
                      (H == 1 & H_entry == "-1" & H_exit == 0) |#special case first hour
                      (H == 24 & exit_corrected_fact == 1)#special case last hour
                    ) %>%
      dplyr::group_by(H_entry) %>%
      dplyr::summarise(n = sum(n)) %>%
      dplyr::mutate(Hour = H) %>%
      dplyr::ungroup()
  }) %>%
    dplyr::bind_rows() %>%
    dplyr::mutate(H_entry = factor(H_entry, levels = c("-1", 0:23)),#ensure every time is present after the next "complete"
                  Hour = factor(Hour, levels = c(1:24))) %>%
    tidyr::complete(H_entry,
                    Hour,
                    fill = list(n = 0)) %>%
    dplyr::mutate(H_entry = as.numeric(as.character(H_entry)),#revert to the numeric type
                  Hour = as.numeric(as.character(Hour)))

  tab_n$n_strata = n_strata
  tab_n$n_days = n_days
  
  tab_n$n_avg = tab_n$n/(n_days*n_strata)

  return(tab_n)
  }
