# WARNING - Generated by {fusen} from dev/flat_plot_urgara.Rmd: do not edit by hand

#' plot charge diagram
#' 
#' plot a charge diagram from the "tab_charge" object created by plot_diag_charge()
#' 
#' @param data data passed from plot_diag_charge
#' @param tab_charge table created by fct_tab_charge
#' @inheritParams plot_diag_charge
#'
#' @return a ggplot
#' @noRd
fct_plot_charge <- function(data, tab_charge, max_LOS){
  #computation of the number of entry/exit per hour
  tab_entry <- data %>%
    dplyr::filter(.data$LOS < max_LOS) %>%
    dplyr::mutate(Hour = lubridate::hour(.data$dh_entry) + 1,
                  Hour = factor(.data$Hour, levels = c(1:24))) %>%
    dplyr::group_by(.data$Hour, .drop = F) %>%
    dplyr::count() %>%
    dplyr::mutate(Hour = as.numeric(as.character(.data$Hour)),
                  n_days = dplyr::first(tab_charge$n_days),
                  n_strata = dplyr::first(tab_charge$n_strata),
                  n_avg = .data$n/(.data$n_days*.data$n_strata)) %>%
    dplyr::ungroup()

  tab_exit <- data %>%
    dplyr::filter(.data$LOS < max_LOS) %>%
    dplyr::mutate(Hour = lubridate::hour(.data$dh_exit) + 1,
                  Hour = factor(.data$Hour, levels = c(1:24))) %>%
    dplyr::group_by(.data$Hour, .drop = F) %>%
    dplyr::count() %>%
    dplyr::mutate(Hour = as.numeric(as.character(.data$Hour)),
                  n_days = dplyr::first(tab_charge$n_days),
                  n_strata = dplyr::first(tab_charge$n_strata),
                  n_avg = .data$n/(.data$n_days*.data$n_strata)) %>%
    dplyr::ungroup()
  
  #Creation of a color palet
  pal1 <- RColorBrewer::brewer.pal(8, "Accent")
  pal2 <- RColorBrewer::brewer.pal(8, "Dark2")
  pal3 <- RColorBrewer::brewer.pal(8, "Set2")
  if(tab_charge %>% dplyr::filter(.data$H_entry < 0) %>% dplyr::pull(.data$n) %>% sum > 0){#at least one patient from the day before => add black to the front of the palette
    pal <- c("black", pal1, pal2, pal3)
  } else {#if no patients are from the day before black is not used
    pal <- c(pal1, pal2, pal3)
  }
  
  #plot rendering
  plot <- ggplot2::ggplot(tab_charge, ggplot2::aes()) +
    ggplot2::geom_density(ggplot2::aes(y = .data$n_avg, x = as.numeric(.data$Hour), fill = factor(.data$H_entry, levels = c("-1", 0:23))),
                          stat = "identity",  position = "stack", color = NA) +
    ggplot2::geom_line(ggplot2::aes(y = .data$n_avg, x = .data$Hour, color = "Nombre d'entr\u00E9es"), data = tab_entry, linewidth = 1.2) +
    ggplot2::geom_line(ggplot2::aes(y = .data$n_avg, x = .data$Hour, color = "Nombre de sorties"), data = tab_exit, linewidth = 1.2) +
    ggplot2::scale_fill_manual(values = pal) +
    ggplot2::scale_x_continuous(name = "", breaks = seq(1,24, by = 1),
                                labels = paste0("< ", seq(1,24, by = 1), "h")) +
    ggplot2::scale_y_continuous(name = "Nombre moyen de patients", breaks = scales::pretty_breaks(10)) +
    ggplot2::scale_color_manual(name = "", values = c("Nombre d'entr\u00E9es" = "darkgreen", "Nombre de sorties" = "darkred")) +
    ggplot2::coord_cartesian(xlim = c(1,24), ylim = c(0,NA)) +
    ggpubr::theme_pubclean() +
    ggplot2::guides(fill = "none") +
    ggplot2::theme(text=ggplot2::element_text(family="serif", size=15)) +
    ggplot2::theme(legend.position = "bottom",
                   legend.key = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
  
    return(plot)
}

#' Charge table
#' 
#' Internal function. Makes a charge table with one line per hour of the day (entry) per hour of the day (exit) and returns a charge table used to plot a charge diagram
#' 
#' @param data tibble with two columns, dh_entry and dh_exit
#' @inheritParams plot_diag_charge
#' 
#' @return a tibble
#' 
#' @noRd
fct_tab_charge <- function(data, from, to, max_LOS){
  #denominator
  n_days <- as.numeric(1 + difftime(to, from, units = "days"))
  if("strata" %in% names(data)){
    n_strata <- length(unique(data$strata))
  } else{n_strata = 1}
 
  #winsorisation of entry and exit to from and to
  data$entry_corrected_fact = lubridate::date(data$dh_entry) < from
  data$dh_entry_corrected = dplyr::if_else(data$entry_corrected_fact,
                                           lubridate::ymd_hms(paste(from, "00:00:00")),
                                           data$dh_entry)
  
  data$exit_corrected_fact = lubridate::date(data$dh_exit) > to
  data$dh_exit_corrected = dplyr::if_else(data$exit_corrected_fact,
                                          lubridate::ymd_hms(paste(to, "23:59:59")),
                                          data$dh_exit)

  #Computation of intermediary variables
  data_interm <- data %>%
    dplyr::mutate(#recomputation LOS and entry times after winsorization
      LOS = as.numeric(difftime(.data$dh_exit_corrected, .data$dh_entry_corrected, units = "mins")),
      H_entry = lubridate::hour(.data$dh_entry_corrected),
      H_exit = lubridate::hour(.data$dh_exit_corrected),
      entry_minute = .data$H_entry*60 + lubridate::minute(.data$dh_entry_corrected),#entry time in minutes since midnight
      d_entry_corrected = lubridate::date(.data$dh_entry_corrected),
      d_exit_corrected = lubridate::date(.data$dh_exit_corrected)
    ) %>%
    dplyr::select("entry_minute", "LOS", "entry_corrected_fact", "H_entry",
                  "H_exit", "d_entry_corrected", "d_exit_corrected") %>%
    dplyr::mutate(exit_minute = .data$entry_minute + .data$LOS,
                  H_exit_comp = .data$exit_minute %/% 60,#hour of exit with 00h of entry day (can be over 23h59)
                  H_exit_corrected = dplyr::if_else(.data$d_entry_corrected < .data$d_exit_corrected, 23, as.numeric(.data$H_exit)),#winsorizing it to 23hxx
                  exit_corrected_fact = as.numeric(.data$d_entry_corrected < .data$d_exit_corrected),
                  nb_cycles = .data$H_exit_comp %/% 24,#number of times 24h fit in the LOS
                  nb_cycles = dplyr::if_else(.data$nb_cycles == 0 & .data$d_entry_corrected < .data$d_exit_corrected, 
                                             1, .data$nb_cycles),#correct an edge case
                  H_exit_last_cycle = .data$H_exit,
                  H_entry = dplyr::if_else(.data$entry_corrected_fact, -1, as.numeric(.data$H_entry)))

  #Number of "full cycles" to add (patient present from 00h01 to 23h59)
  nb_H24_add = data_interm  %>%
    dplyr::filter(.data$nb_cycles > 0) %>%
    dplyr::summarise(nb_cycle_tot = sum(.data$nb_cycles - 1)) %>%
    dplyr::pull(.data$nb_cycle_tot)

  #table of "full cycles" 
  tab_full_day_supp <- tibble::tibble(
    H_entry = rep(-1, nb_H24_add),
    H_exit = rep(23, nb_H24_add),
    exit_corrected_fact = 1
  ) %>%
    dplyr::mutate_all(as.numeric)

  #table of "half cycles" to add (patient arrived the day before and leaves this day)
  tab_final_day <- tibble::tibble(#ajout de x lignes correpsond à des passages -1 à "heure de sortie dernier cycle)
    H_entry = -1,
    H_exit = data_interm %>% dplyr::filter(.data$nb_cycles > 0) %>% dplyr::pull(.data$H_exit_last_cycle),
    exit_corrected_fact = 0
  ) %>%
    dplyr::mutate_all(as.numeric)

  #merge of full cycles, half cycles and first days
  data_calc_charge = dplyr::bind_rows(data_interm %>% dplyr::select("H_entry", "H_exit" = "H_exit_corrected", "exit_corrected_fact"),
                                      tab_full_day_supp,
                                      tab_final_day)

  #Speed up following computation by merging indentical rows
  data_calc_charge_agreg = data_calc_charge %>%
    dplyr::group_by(.data$H_entry, .data$H_exit, .data$exit_corrected_fact) %>%
    dplyr::count()
  
  #For each hour of the day, count the number of patient present from wich time of arrival (-1 = day before)
  tab_n = lapply(seq(1, 24, by = 1), function(H){
    data_calc_charge_agreg %>%
      dplyr::filter((.data$H_entry < H & .data$H_exit >= H) |
                      (.data$H_entry == H -1 & .data$H_exit == H - 1 & .data$exit_corrected_fact == 0) |
                      (H == 1 & .data$H_entry == "-1" & .data$H_exit == 0) |#special case first hour
                      (H == 24 & .data$exit_corrected_fact == 1)#special case last hour
                    ) %>%
      dplyr::group_by(.data$H_entry) %>%
      dplyr::summarise(n = sum(.data$n)) %>%
      dplyr::mutate(Hour = H) %>%
      dplyr::ungroup()
  }) %>%
    dplyr::bind_rows() %>%
    dplyr::mutate(H_entry = factor(.data$H_entry, levels = c("-1", 0:23)),#ensure every time is present after the next "complete"
                  Hour = factor(.data$Hour, levels = c(1:24))) %>%
    tidyr::complete(.data$H_entry,
                    .data$Hour,
                    fill = list(n = 0)) %>%
    dplyr::mutate(H_entry = as.numeric(as.character(.data$H_entry)),#revert to the numeric type
                  Hour = as.numeric(as.character(.data$Hour)))

  tab_n$n_strata = n_strata
  tab_n$n_days = n_days
  
  tab_n$n_avg = tab_n$n/(n_days*n_strata)

  return(tab_n)
  }

#' Add company logo to a plot
#' 
#' @description Adds a company logo (by default Urg'Ara) to a plot. A custom logo can be used by specifying a path to the logo
#' 
#' @param plot A ggplot object
#' @param logo The path to an image file. If NULL, the Urg'Ara logo will be used instead
#' @param height The height of the logo in proportion of the graph (default 0.1)
#' @param width The width of the logo in proportion of the graph (default 0.2)
#' @param position The position of the logo. Possible values are "bottom right", "bottom", "bottom left", "top right", "top", "top left"
#' @param remove.margin Should the margin of the plot be removed on the side of the logo for a more precise fit
#' 
#' @return a ggplot2 object
#' 
#' @export
#' @examples
#' library(rUrgAra)
#' library(ggplot2)
#' plot_cars = ggplot(cars, ggplot2::aes(x = speed, y = dist)) +
#'   geom_point() +
#'   ggpubr::theme_pubclean()
#'
#' plot_add_logo(plot_cars)#default
#' plot_add_logo(plot_cars, position = "top left")#logo at the top
#' plot_add_logo(plot_cars, width = 0.4)#wider logo
plot_add_logo <- function(plot, logo = NULL, height = 0.1, width = 0.2, 
                          position = c("bottom right", "bottom", "bottom left",
                                       "top right", "top", "top left"),
                          remove.margin = TRUE){
  #type check
  if(!is.numeric(height) | !is.numeric(width)){
    stop("Height and width must be numerical")} else
      if(!dplyr::between(height, 0, 1) | !dplyr::between(width, 0, 1)){
        stop("Height and width myst be between 0 and 1")
      }
  if(!is.character(position)){stop("position must be a character vector")} else
    if(!position[1] %in% c("bottom right", "bottom", "bottom left",
                           "top right", "top", "top left")){
      stop("Wrong value for position. Check the help page for a list of allowed values")
    }
  if(!ggplot2::is.ggplot(plot)) stop("plot must be a ggplot object")
  if(!is.null(logo)){
    if(!stringr::str_detect(logo, ".jpg$")) stop("Logo must point to a .jpg file")
    if(!file.exists(logo)) stop(paste0(logo, " does not exist"))
  }

  #removing margins of input plot
  if(remove.margin){
    if(grepl("^top", position[1])){
          plot = plot + 
            ggplot2::theme(plot.margin = ggplot2::margin(t = 0))
    } else if(grepl("^bottom", position[1])){
          plot = plot + 
            ggplot2::theme(plot.margin = ggplot2::margin(b = 0))
    }
  }
  
  #loading of the logo 
  if(is.null(logo)){logo = paste0(path.package(package = "rUrgAra"), "/img/logo_urgara.jpg")}
  logo_img = magick::image_read(logo)
  
  #resolution of position
  xy = dplyr::case_when(
    position[1] == "bottom right" ~ c(1-width, 0),
    position[1] == "bottom" ~ c(0.5-(width/2), 0), 
    position[1] == "bottom left" ~ c(0, 0),
    position[1] == "top right" ~ c(1-width, 1-height), 
    position[1] == "top" ~ c(0.5-(width/2), 1-height), 
    position[1] == "top left" ~ c(0, 1-height)
  )
  #y coordinate of the plot (0 if logo at the top, 0+heigth if logo at the bottom)
  y_plot = dplyr::if_else(xy[2] == 0, 0 + height, 0)
  
  #adding logo image to the plot at designated coordinates
  plot_logoed = cowplot::ggdraw() +
    cowplot::draw_plot(plot, x = 0, y = y_plot, width = 1, height = 1-height) +
    cowplot::draw_image(logo_img, x = xy[1], y = xy[2], width = width, height = height)
   
  return(plot_logoed)
}
