# WARNING - Generated by {fusen} from dev/flat_plot_urgara.Rmd: do not edit by hand

#' Plot a charge diagram
#' 
#' @description Plot a charge diagram from a table with an entre datetime and exit datetime. A charge diagram shows the number of individuals and their time of arrival for each hour/half hour of a day.
#' 
#' @param data A data frame or tibble.
#' @param entry The name of the column containing the datetime of entry. The colmum must be of class POSIXct or character in the format DD/MM/YYYY HH:MM:SS.
#' @param exit The name of the column containing the datetime of exit. The colmum must be of class POSIXct or character in the format DD/MM/YYYY HH:MM:SS.
#' @param strata The name of the colum(s) containing statas (e.g. structures) to average the charge over.
#' @param from The start of the time frame to consider (dmy). Number of patients will be averaged over the number of days between "from" and "to" and entry date/times will be truncated at "from". Default value is the minimum date in the entry column.
#' @param to The end of the time frame to consider (dmy). Number of patients will be averaged over the number of days between "from" and "to" and exit date/times will be truncated at "to". Default value is the maximum date in the exit column.
#' @param max_LOS Maximum length of stay for patients in minutes. Patients with durations longer than max_LOS will be considered as having missing length of stay.
#' 
#' @return A list. tab contains the table used to make the charge diagram. H_entry = "-1" for patients entered the day before. plot contains the charge diagram.
#' 
#' @export
#' 
#' @examples
#' library(rUrgAra)
#' #Table of entry/exit times
#' head(df_ex_charge)
#' #Charge diagram with exclusion of patients staying more than 3 days (72*60 = 4320 minutes)
#' # not taking into account strata 
#' list_charge = plot_diag_charge(data = df_ex_charge, entry = "ENTREE",
#'                                exit = "SORTIE", max_LOS = 72*60)
#' #plot_diag_charge return two objects, a table showing for each hour of
#' # the day how many patient came from what hour (-1 = day before)
#' head(list_charge$tab)
#' #a charge diagram
#' list_charge$plot
#'
#' #adding a strata to take into account that data are coming from two hospitals
#' list_charge_stratified = plot_diag_charge(data = df_ex_charge, entry = "ENTREE",
#'                                           exit = "SORTIE", strata = "Etablissement",
#'                                           max_LOS = 72*60)
#' #plot_diag_charge return two objects, a table showing for each hour of
#' # the day how many patient came from what hour (-1 = day before)
#' head(list_charge_stratified$tab)
#' #a charge diagram
#' list_charge_stratified$plot
#'
plot_diag_charge <- function(data, entry, exit, strata = NULL,
                             from = NULL, to = NULL, max_LOS = Inf){
  #type check
  type_entry = dplyr::pull(data, entry) %>% class
  type_exit = dplyr::pull(data, exit) %>% class
  if(any(type_entry != type_exit))stop("entry and exit must have the same type")
  format_to_from_ok = function(x){#testing format param from and to
    if(is.null(x)) return(TRUE)
    if(length(x) >= 1 | !is.character(x)) return(FALSE)
    if(!is.na(lubridate::dmy(x))) return(TRUE)
    return(FALSE)
  }
  if(!format_to_from_ok(from)){stop("from must be NULL or a character string containing a date in the DMY format")}
  if(!format_to_from_ok(to)){stop("to must be NULL or a character string containing a date in the DMY format")}
  if(!is.numeric(max_LOS) | max_LOS <= 0){stop("max_LOS must be numeric and positive")}
  
  #rename entry/exit/strata column
  data <- data %>%
    dplyr::select(dh_entry = {entry}, dh_exit = {exit}, strata = {strata})
  
  #convertion to dmy_hms
  if(is.character(data$dh_entry)){
    data <- data %>%
      dplyr::mutate(dplyr::across(c("dh_entry", "dh_exit"), lubridate::dmy_hms))
  }
  
  #handling of default values for "from", "to"
  if(is.null(from)){from = min(lubridate::date(data$dh_entry), na.rm = T)} else {from = lubridate::dmy(from)}
  if(is.null(to)){to = max(lubridate::date(data$dh_exit), na.rm = T)} else {to = lubridate::dmy(to)}
  
  #Removing delays over max_LOS
  data$LOS = difftime(data$dh_exit, data$dh_entry, units = "mins")
  LOS_over = data$LOS > max_LOS
  if(sum(data$LOS > max_LOS, na.rm = T) > 0){
    warning(paste(sum(data$LOS > max_LOS, na.rm = T),
                  "delays have been removed because of length of stay superior to", 
                  max_LOS, "minutes"))}
  data = data %>% dplyr::filter(!LOS_over)
  
  #computation of the table of charge
  tab_charge <- fct_tab_charge(data = data, from = from, to = to, max_LOS = max_LOS)
  
  #plotting of the charge diagram
  plot_charge <- fct_plot_charge(data = data, tab_charge = tab_charge, max_LOS = max_LOS)
  
  return(list(tab = tab_charge,
              plot = plot_charge))
}
