# WARNING - Generated by {fusen} from dev/flat_plot_urgara.Rmd: do not edit by hand

#' Add company logo to a plot
#' 
#' @description Adds a company logo (by default Urg'Ara) to a plot. A custom logo can be used by specifying a path to the logo
#' 
#' @param plot A ggplot object
#' @param logo The path to a .jpg logo. If NULL, the Urg'Ara logo will be used instead
#' @param height The height of the logo in proportion of the graph (default 0.1)
#' @param width The width of the logo in proportion of the graph (default 0.2)
#' 
#' @return a ggplot2 object
#' 
#' @export
#' @examples
#' library(ggplot2)
#' plot_test = ggplot(data.frame(), ggplot2::aes(x = 1, y = 1)) +
#'   geom_point()
#' plot_add_logo(plot = plot_test)
plot_add_logo <- function(plot, logo = NULL, height = 0.1, width = 0.2){
  #type check
  if(!is.numeric(height) | !is.numeric(width)){
    stop("Height and width must be numerical")} else
      if(!dplyr::between(height, 0, 1) | !dplyr::between(width, 0, 1)){
        stop("Height and width myst be between 0 and 1")
      }
  if(!ggplot2::is.ggplot(plot)) stop("plot must be a ggplot object")
  if(!is.null(logo)){
    if(!stringr::str_detect(logo, ".jpg$")) stop("Logo must point to a .jpg file")
    if(!file.exists(logo)) stop(paste0(logo, " does not exist"))
  }

  
  #creation of a ggplot containing the logo
  if(is.null(logo)){logo = paste0(path.package(package = "rUrgAra"), "/img/logo_urgara.jpg")}
  logo_jpg = grid::rasterGrob(jpeg::readJPEG(logo), interpolate = T)
  plot_logo = ggplot2::ggplot(mapping = ggplot2::aes(x = 1, y = 1)) +
    ggplot2::theme_void() +
    ggplot2::annotation_custom(logo_jpg)
  
  #Making a grid.arrange with the input plot and the logo
  plot_logoed <- gridExtra::grid.arrange(grobs = list(plot +
                                                        ggplot2::theme(plot.margin = ggplot2::margin(t = 0)),
                                                      plot_logo +
                                                        ggplot2::theme(plot.margin = ggplot2::margin(t = 0, 0, 0, 0))),
                                         heights = c(1-height, height), widths = c(1-width, width),
                                         layout_matrix = rbind(c(1, 1),
                                                               c(NA, 2)))
  return(plot_logoed)
}
